import type { ChangePlan, DiffPreview, GeneratedFile } from "@/lib/types/core";

export function createDiffPreview(plan: ChangePlan): DiffPreview {
  const files = createGeneratedFiles(plan);

  return {
    planId: plan.id,
    files,
    riskNotes: plan.risk.reasons
  };
}

function createGeneratedFiles(plan: ChangePlan): GeneratedFile[] {
  const slug = slugify(plan.intent.request);
  const title = toTitle(plan.intent.request);

  return [
    {
      path: `generated/${slug}/index.html`,
      language: "html",
      summary: "Creates a previewable website shell for the approved request.",
      after: createHtml(title, plan.intent.interpretedGoal)
    },
    {
      path: `generated/${slug}/styles.css`,
      language: "css",
      summary: "Adds a clean responsive visual system for the generated preview.",
      after: createCss()
    },
    {
      path: `generated/${slug}/README.md`,
      language: "markdown",
      summary: "Documents how the generated preview should be reviewed.",
      after: `# ${title}\n\nGenerated by VerityOS after plan approval.\n\nReview the preview, inspect the diff, then run verification before shipping.\n`
    }
  ];
}

function createHtml(title: string, goal: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <main class="shell">
      <section class="hero">
        <p class="eyebrow">Generated Preview</p>
        <h1>${escapeHtml(title)}</h1>
        <p>${escapeHtml(goal)}</p>
        <div class="actions">
          <a href="#details">Review plan</a>
          <a class="secondary" href="#validation">Validation</a>
        </div>
      </section>
      <section id="details" class="grid">
        <article>
          <h2>Purpose</h2>
          <p>This preview shows the user-facing surface that would be created after approval.</p>
        </article>
        <article>
          <h2>Safety</h2>
          <p>No repository files are mutated until the plan, diff, and validation gate are accepted.</p>
        </article>
        <article id="validation">
          <h2>Evidence</h2>
          <p>Typecheck, build, test, route, API, and visual checks remain required before release.</p>
        </article>
      </section>
    </main>
  </body>
</html>`;
}

function createCss(): string {
  return `:root {
  color: #111827;
  background: #f7f8fa;
  font-family: Inter, ui-sans-serif, system-ui, sans-serif;
}

body {
  margin: 0;
}

.shell {
  min-height: 100vh;
  padding: 48px;
}

.hero {
  max-width: 920px;
  padding: 48px;
  background: #ffffff;
  border: 1px solid #dbe2ea;
}

.eyebrow {
  color: #1f7a5b;
  font-size: 13px;
  font-weight: 700;
  text-transform: uppercase;
}

h1 {
  max-width: 760px;
  font-size: 56px;
  line-height: 1;
}

p {
  color: #425160;
  font-size: 18px;
  line-height: 1.7;
}

.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 28px;
}

a {
  display: inline-flex;
  padding: 12px 16px;
  background: #111827;
  color: #ffffff;
  text-decoration: none;
  font-weight: 700;
}

a.secondary {
  background: #eef2f6;
  color: #111827;
}

.grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 16px;
  max-width: 1100px;
  margin-top: 24px;
}

article {
  padding: 24px;
  background: #ffffff;
  border: 1px solid #dbe2ea;
}

@media (max-width: 780px) {
  .shell {
    padding: 20px;
  }

  .hero {
    padding: 28px;
  }

  h1 {
    font-size: 40px;
  }

  .grid {
    grid-template-columns: 1fr;
  }
}`;
}

function slugify(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "preview";
}

function toTitle(value: string): string {
  return value
    .trim()
    .split(/\s+/)
    .map((word) => word.slice(0, 1).toUpperCase() + word.slice(1))
    .join(" ");
}

function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

