export interface PRBodyInput {
  taskDescription: string;
  changedFiles: Array<{ path: string; added: number; removed: number }>;
  blastRadiusSummary: string;
  controlGateResult: { passed: boolean; summary: string };
  securityScanStatus: "passed" | "not_run" | "failed";
  completionEvaluatorResult: { passed: boolean; summary: string };
  bootRiseVersion: string;
}

export function buildWorkspacePrBody(input: PRBodyInput): string {
  const securityWarning =
    input.securityScanStatus === "passed"
      ? "Security scan passed."
      : input.securityScanStatus === "failed"
        ? "Security scan failed. Resolve blockers before production deploy."
        : "Security scan was not run before this PR.";

  return [
    "# BootRise Draft PR",
    "",
    "## Task summary",
    input.taskDescription,
    "",
    "## Changed files",
    input.changedFiles.length
      ? input.changedFiles.map((file) => `- \`${file.path}\` (+${file.added}/-${file.removed})`).join("\n")
      : "- No changed files were reported.",
    "",
    "## Blast radius",
    input.blastRadiusSummary,
    "",
    "## Control result",
    `${input.controlGateResult.passed ? "Passed" : "Blocked"} - ${input.controlGateResult.summary}`,
    "",
    "## Security status",
    securityWarning,
    "",
    "## Completion evaluator",
    `${input.completionEvaluatorResult.passed ? "Passed" : "Needs review"} - ${input.completionEvaluatorResult.summary}`,
    "",
    `Generated by BootRise ${input.bootRiseVersion}.`
  ].join("\n");
}
